- name: CreatingUserwithPasswordlessSudo
  hosts: all
  become: true
  vars:
    sudo_users:
      - alice
      - bob
      - carl
  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item }}"
        groups: wheel
        append: true
        shell: /bin/bash
        create_home: true
      loop: "{{ sudo_users }}"

    - name: Create passwordless sudo for users
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ item }}"
        content: "{{ item }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: "0440"
        validate: 'visudo -cf %s'
      loop: "{{ sudo_users }}"
