# Create a new user devuser and copy your local SSH public key to their ~/.ssh/authorized_keys file.
- name: Playbook for ssh access
  hosts: all
  become: true
  gather_facts: false
  vars:
    pub: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJlhgoCnW9dqCFsXhO3E98Ck6GrqUo3f8Z85ZtOciJed saket.98b@gmail.com"
    user: devuser
  tasks:
    - name: Create user {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"
        create_home: true
        shell: /bin/bash

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        owner: "{{ user }}"
        mode: "0700"

    - name: Add authorized key
      ansible.builtin.authorized_key:
        user: "{{ user }}"
        key: "{{ pub }}"
        state: present

    - name: Grant passwordless sudo to {{ user }}
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ user }}"
        content: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
        owner: root
        group: root
        mode: "0440"
        validate: 'visudo -cf %s'
