- name: testing out systemd module
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Collect service facts
      ansible.builtin.service_facts:

    - name: Collect installed package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Start nginx if installed
      ansible.builtin.systemd_service:
        name: nginx
        state: started
      when: "'nginx' in ansible_facts.packages"

    - name: Fail if nginx service is not running
      ansible.builtin.fail:
        msg: "Nginx is not running!"
      when:
        - "'nginx.service' in ansible_facts.services"
        - ansible_facts.services['nginx.service'].state != 'running'

    - name: Stop crond if present
      ansible.builtin.systemd_service:
        name: crond
        state: stopped
      when: "'crond.service' in ansible_facts.services"

    - name: Ensure sshd is running and enabled
      ansible.builtin.systemd_service:
        name: sshd
        state: started
        enabled: true
      when: "'sshd.service' in ansible_facts.services"

    - name: Disable and stop firewalld if present
      ansible.builtin.systemd_service:
        name: firewalld
        state: stopped
        enabled: false
      when: "'firewalld.service' in ansible_facts.services"

    - name: Show installed packages
      ansible.builtin.debug:
        var: ansible_facts.packages
