---
- name: lab 4 repeat
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: install httpd package
      dnf:
        name: httpd
        state: present
    - name: starting httpd
      service:
        name: httpd 
        enabled: yes
        state: started
    - name: firewall settings for httpd
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
    - name: creating index.html
      copy:
        dest: /var/www/html/index.html
        content: > 
                "Welcome Saket"
        
